"""empty message

Revision ID: 2c930e594759
Revises: 5415e7d23957
Create Date: 2018-10-04 18:33:45.433609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c930e594759'
down_revision = '5415e7d23957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('create_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'create_date')
    # ### end Alembic commands ###
