"""empty message

Revision ID: 89fa7f7eddb3
Revises: 2c930e594759
Create Date: 2018-10-08 12:57:50.816987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89fa7f7eddb3'
down_revision = '2c930e594759'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('slug', sa.String(length=244), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('image', sa.String(length=244), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fuels',
    sa.Column('slug', sa.String(length=244), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('segments',
    sa.Column('slug', sa.String(length=244), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.CHAR(length=3), nullable=True),
    sa.Column('description', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cars',
    sa.Column('slug', sa.String(length=244), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('segment_id', sa.INTEGER(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['segment_id'], ['segments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_brand_id'), 'cars', ['brand_id'], unique=False)
    op.create_index(op.f('ix_cars_segment_id'), 'cars', ['segment_id'], unique=False)
    op.create_table('car_variants',
    sa.Column('slug', sa.String(length=244), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fuel_id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('variant', sa.String(length=244), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.ForeignKeyConstraint(['fuel_id'], ['fuels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_car_variants_car_id'), 'car_variants', ['car_id'], unique=False)
    op.create_index(op.f('ix_car_variants_fuel_id'), 'car_variants', ['fuel_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_car_variants_fuel_id'), table_name='car_variants')
    op.drop_index(op.f('ix_car_variants_car_id'), table_name='car_variants')
    op.drop_table('car_variants')
    op.drop_index(op.f('ix_cars_segment_id'), table_name='cars')
    op.drop_index(op.f('ix_cars_brand_id'), table_name='cars')
    op.drop_table('cars')
    op.drop_table('segments')
    op.drop_table('fuels')
    op.drop_table('brands')
    # ### end Alembic commands ###
